name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set up nodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          nx test frontend
          nx test backend